name: Bug Report
description: File a bug report for an issue affecting our Minecraft Server, Website, Discord, or our Public API.
title: "Bug | "
labels: "type: requires triage"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report! It helps to make our services better for everyone!
  - type: dropdown
    id: platform
    attributes:
      label: Where are you experiencing this issue?
      multiple: true
      options:
        - API
        - Discord
        - Minecraft Server
        - Website
  - type: textarea
    id: bug_description
    attributes:
      label: Explain the bug.
      description: Please describe what you experienced.
      placeholder: The Ender Slayer's Sword fails to death 45% more damage then a normal sword.
    validations:
      required: true
  - type: textarea
    id: bug_replication_steps
    attributes:
      label: How can we replicate your bug?
      description: Provide a step-by-step to allow one of our Issue Moderators or developers to replicate your issue.
      placeholder: |
        1. Obtain a Ender Slayer's Sword.
        2. Ensure that you're a Rogue class.
        3. Attack any Ender mob.
        4. Notice that it doesn't deal 45% extra damage.
        5. Profit...
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: What were you expecting to happen?
      description: Please describe what you where expecting to happen before encountering the bug.
      placeholder: "I was expecting the weapon to work properly."
    validations:
      required: true
  - type: dropdown
    id: attempted_replications
    attributes:
      label: How many times did you attempt to replicate this bug?
      description: We recommend testing any issue 3 times.
      options:
        - 1-3 Times
        - 3-6 Times
        - 6-9 Times
        - 10 Times
    validations:
      required: true
  - type: input
    id: successful_replications
    attributes:
      label: Of the times you tested, how many produced the issue?
      description: Please list your maximum amount of tries with your successful ones.
      placeholder: 5/10
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Agreements
      description: By submitting this issue, you agree that you've used the search function to see if there are any relevant issues already opened before opening this report.
      options:
        - label: I agree
          required: true
