blank_issues_enabled: false
contact_links:
  - name: ShadowsMC Customer Support
    url: https://support.shadowsmc.net/
    about: If you have an issue that involves personal or sensitive data, please open a report here.